version: 2.1

workflows:
  commit-workflow:
    jobs:
      - build
  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - test
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/php:8.3.2
    steps:
      - checkout:
          path: ~/project
      # Build project dockerfile image
      #- setup_remote_docker:
      #    docker_layer_caching: true
      #- run:
      #    name: Build image
      #    command: docker build .
      - run:
          name: Install packages
          command: composer install
