version: 2.1

workflows:
  deploy:
    jobs:
    - build

jobs:
  build:
    working_directory: ~/circleci
    docker:
      - image: cimg/php:8.3.2
    steps:
      #- checkout Permission denied (publickey).
      - run:
          name: See files
          command: ls ~/home/circleci/.ssh
          # bin  circleci  project
      - checkout
      - run:
          name: Install packages
          command: composer install
