version: 2.1

workflows:
  deploy:
    jobs:
    - build

jobs:
  build:
    docker:
      - image: cimg/php:8.3.2
    steps:
      #- checkout Permission denied (publickey).
      - run: php --version
